### ISSUE TITLE
Cannot get the updater.check

### ISSUE THREAD

**Issue by Timmy31** [pietrocinaglia/laraupdater#1]
I tried using this updater but I get this error:
GET http://localhost/ProjectName/public/updater.check 500 (Internal Server Error)

I dont know whether is become of jquery version. Details of the issue are:
send @ jquery-3.1.1.min.js:4
ajax @ jquery-3.1.1.min.js:4
(anonymous) @ system_update:323
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
fire @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
ready @ jquery-3.1.1.min.js:2

**Comment by pietrocinaglia** [comment]
Hi FitimFejzullahu, check CHMOD permissions for 'tmp_path' (see doc) and related update-files (e.g. zip and metadata), as well as the jquery into your view (you have to import the lib).
keep in touch... :)
