### ISSUE TITLE
how to work if laravel and public_html 

### ISSUE THREAD

**Issue by MFakhrani** [pietrocinaglia/laraupdater#15]
hey
My project folder is as follows:

laravel ---> source code
public_html ---> public

However, I get the following error during the update operation
Thank you for helping me

laraupdater.UPDATE_FOUND: 1.0.2 (laraupdater.current_version: 1.0)

laraupdater.DESCRIPTION: Minor bugs fix

» laraupdater.Update_downloading_..

laraupdater.ERROR_DURING_UPDATE_(!!check_the_update_archive!!)Exception => The "C:\xampp\htdocs\test\laravel/backup_20191227" directory does not exist.
[ laraupdater.FAILED ]
laraupdater.Backup_folder_is_located_in: C:\xampp\htdocs\test\laravel/backup_20191227.
laraupdater.Remember_to_restore_System_UP-Status_through_shell_command: php artisan up.

**Comment by TechTailor** [comment]
Instead of putting your public directory inside public_html you should keep it inside your laravel folder and then just point your sub-domian/domain to laravel/public.

**Comment by Mo7mud** [comment]
@MFakhrani  How did you solve this?
