### ISSUE TITLE
 ERROR  Can't locate path: <vendor/pcinaglia/laraupdater/src/../config/laraupdater.php>.

### ISSUE THREAD

**Issue by mohamad-supangat** [pietrocinaglia/laraupdater#29]
error while running a command
```bash
php artisan vendor:publish --provider="pcinaglia\laraupdater\LaraUpdaterServiceProvider"
```
![image](https://user-images.githubusercontent.com/48933993/216497534-386d1241-fdea-44d0-b72d-e7b7b936c7f5.png)

using:
laravel/framework: v9.50.2

**Comment by pietrocinaglia** [comment]
Thanks so much for your comment, and your fix :)
